### ISSUE TITLE
Add author information

### ISSUE THREAD

**Issue by LQClayton** [Lordfirespeed/progblack_formative_1#12]
Please can everyone who hasn't linked websites & information do so. Thanks

**Comment by LQClayton** [comment]
@Lordfirespeed which county are you from? @busymaestro @Antriksh1811 do you have links to your websites?

**Comment by Lordfirespeed** [comment]
> @Lordfirespeed which county are you from? @busymaestro @Antriksh1811 do you have links to your websites?

"Joe lives in Oxfordshire. He enjoys playing puzzle/escape games such as Portal in his free time."
